apiVersion: v1
kind: Pod
metadata:
  name: trade-store-server
  labels: {
    app: trade-store-server
  }
spec:
  containers:
    - image: ktune/se-simulator:trade-store-server
      name: trade-store-server
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: trade-store-server
spec:
  selector:
    app: trade-store-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: trade-data-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-data-gen
  template:
    metadata:
      labels:
        app: trade-data-gen
    spec:
      containers:
      - name: trade-data-gen
        image: ktune/se-simulator:tradeGen
---
apiVersion: v1
kind: Pod
metadata:
  name: aerospike
  labels: {
    app: aerospike
  }
spec:
  containers:
    - image: aerospike:ce-5.6.0.5
      name: aerospike
      ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: aerospike
spec:
  selector:
    app: aerospike
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000


