# pull official base image
FROM centos/nodejs-10-centos7

RUN git clone -b javalin-0-1 https://github.com/ken-tune/se-simulator.git

RUN cd /se-simulator/fe/sedemo/
# set working directory
WORKDIR /se-simulator/fe/sedemo/

ENV PATH /se-simulator/fe/sedemo/node_modules/.bin:$PATH

# install app dependencies
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# start app
CMD ["npm", "start"]
