FROM node:latest

RUN git clone https://github.com/ken-tune/se-simulator.git && cd /se-simulator && git pull
RUN cd /se-simulator/tradeGen/test && npm install

WORKDIR /se-simulator/tradeGen/test

# Keep it running
ENTRYPOINT ["node", "testServer.js"]
#ENTRYPOINT ["tail","-f","/dev/null"]